version: "3.8"

services:
  backend:
    build:
      context: . # Le contexte est `PoissecailleCalculator`
      dockerfile: backend/Dockerfile # Spécifie le bon Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/app/db
      - ./backend/logs:/app/logs

    environment:
      - TESTING=false
    command:
      [
        "uvicorn",
        "backend.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  backend_db:
  backend_logs:
